### ISSUE TITLE
missing definition

### ISSUE THREAD

**Issue by lmatute** [ayule89/ggplot#1]
ggplot for MMA is a great idea!

In your scratch notebook you use two functions that don't seem to be defined in the repository: "op" and "tidyExpression". Where can I find these definitions?

**Comment by tannerlegvold** [comment]
`importToDataset` as well seems like a necessary function. Note that `SemanticImport` often outputs in terms of datasets and so we may just need to use it here if we had the relevant csv files. Perhaps if the example notebooks simply had an Iconization of the relevant data, `mpg` and `economics`. I agree this is cool project!

**Comment by andrew-yule** [comment]
Thanks for letting me know about this and sorry for the delay.

I've updated the scratch notebook with my latest commit to include the iconized datasets for faster evaluation and also included a definitions section for op/tidyExpression

**Comment by lmatute** [comment]
Great!. Many thanks,

Luis
